name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'

      - run: dotnet restore src/DemoReusableTemplates.csproj   

      - run: dotnet build src/DemoReusableTemplates.csproj 